### Rota signup
POST http://localhost:3000/signup
Content-Type: application/json

{
    "nome": "Pablo",
    "email": "pablo@gmail.com",
    "password": "123456"
}


### Rota signip
POST http://localhost:3000/signin
Content-Type: application/json

{
    "email": "pablo@gmail.com",
    "password": "123456"
}


### Rota signip
POST http://localhost:3000/signin
Content-Type: application/json

{
    "email": "pablolima@gmail.com",
    "password": "123456"
}


###
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NTU0OTgyYzFiYTgzNjkyZDE3ZWFhZSIsImlhdCI6MTcyMDA1NDI3NSwiZXhwIjoxNzIwMDU0MzYxfQ.5L_RImHY5iZregCQ04vltg-FubVsju9mQRhqhIpo7rg
### Rota de Transação
POST http://localhost:3000/transaction
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "value": 150,
    "description": "compras do mes",
    "type": "expense"
}

### Rota de Transação
GET http://localhost:3000/transaction
Content-Type: application/json
Authorization: Bearer {{token}}