### Rota signup
POST http://localhost:3000/signup
Content-Type: application/json

{
    "nome": "Pablo",
    "email": "pablo@gmail.com",
    "password": "123456"
}


### Rota signip
POST http://localhost:3000/signin
Content-Type: application/json

{
    "email": "pablo@gmail.com",
    "password": "123456"
}


### Rota signip
POST http://localhost:3000/signin
Content-Type: application/json

{
    "email": "pablo@gmail.com",
    "password": "123456"
}


###
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NjdhYTlkNGUzMTVlYWViMjJkOWNlMiIsImlhdCI6MTcyMDA1NDk0NSwiZXhwIjoxNzIwMDU1MDMxfQ.7y7AzLvO9TF7-wYEPUw-Hjyj6JcKEqjWr3omLCgY3p
### Rota de Transação
POST http://localhost:3000/transaction
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "value": 150,
    "description": "compras do mes",
    "type": "expense"
}

### Rota de Transação
GET http://localhost:3000/transaction
Content-Type: application/json
Authorization: Bearer {{token}}

### Rota de perfil
GET http://localhost:3000/me
Content-Type: application/json
Authorization: Bearer {{token}}