### Rota signup
POST http://localhost:3000/signup
Content-Type: application/json

{
    "nome": "Pablo",
    "email": "pablo@gmail.com",
    "password": "123456"
}


### Rota signip
POST http://localhost:3000/signin
Content-Type: application/json

{
    "email": "pablo@gmail.com",
    "password": "123456"
}


### Rota signip
POST http://localhost:3000/signin
Content-Type: application/json

{
    "email": "pablolima@gmail.com",
    "password": "123456"
}


###
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NTU0OTgyYzFiYTgzNjkyZDE3ZWFhZSIsImlhdCI6MTcxOTQ1Mzc4NCwiZXhwIjoxNzE5NDUzODcwfQ.zg0N7XeFwnSwJ_PYZxrF6WsDcMJadumbxa986q66Qn4
### Rota de Transação
POST http://localhost:3000/transaction
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "value": 50,
    "description": "Gasolina",
    "type": "expense"
}